# |-----------------------------------------------------------------------------------------------------|
# |   ______     ______     ______   ______     ______     __  __     ______     ______                 |
# |  /\  ___\   /\  __ \   /\  ___\ /\  ___\   /\  ___\   /\ \_\ \   /\  __ \   /\__  _\                |
# |  \ \___  \  \ \  __ \  \ \  __\ \ \  __\   \ \ \____  \ \  __ \  \ \  __ \  \/_/\ \/                |
# |   \/\_____\  \ \_\ \_\  \ \_\    \ \_____\  \ \_____\  \ \_\ \_\  \ \_\ \_\    \ \_\                |
# |    \/_____/   \/_/\/_/   \/_/     \/_____/   \/_____/   \/_/\/_/   \/_/\/_/     \/_/                |
# |-----------------------------------------------------------------------------------------------------|
# Plugin by TheViperShow.
# Config.yml
# Do not touch serialUID unless you know what you're doing!
serialUID: 1
safechat:
  # Send a message to the console whenever one of the checks is verified
  enable-console-logging: false
  database:
    # Allowed types are currently:
    # Values: [POSTGRESQL | MYSQL | SQLITE ]
    # SQLITE database type will use json files to locally store data, so filling the database info fields,
    # such as username, host and passwords will not be required. However if you decide to use PostgreSQL database
    # those fields will be required in order for the plugin to properly connect to the remote\local database!
    type: "SQLITE"
    # The username that will be used when attempting to authenticate into the specified database
    # Values: String
    username: 'username'
    # The password that will be used when attempting to authenticate into the specified database
    # Values: String
    password: 'password'
    # The port that will be used when attempting to connect to the specified database
    # Values: [1-65535]
    port: 5432
    # The address that will be used when attempting to connect to the specified database
    # Values: A valid address, either ipv4 or domain
    # IPv4: https://en.wikipedia.org/wiki/IPv4
    # Domain: https://en.wikipedia.org/wiki/Domain_name
    address: '127.0.0.1'
    # This is the name of the database that the plugin will save data into
    # NOTE: The plugin will not attempt to create a new database, you need to already have an accessible one!
    # Values: Any string
    database: 'database'
    # for display purposes only.
    table: 'safechat_data'
    # This value is really important, it determines how often should the server save the data onto the table.
    # This could avoid data loss after eventual server crashes.
    # recommended value is between 5-15 (minutes)
    # Note that the data will also get saved when the plugin disables.
    auto-save: 5
  # The configuration below uses RegEx to check user input, they are a short sequence of characters that
  # define a search pattern. This are used in order to 'recognize' dangerous messages.
  # You can easily modify them to your own liking, you can find more info here:
  # RegEx: https://en.wikipedia.org/wiki/Regular_expression
  domains:
    enabled: true
    # This regex is used to check domains in the chat which will be blocked.
    regex: "(?i)([a-z0-9]{1,63}[.,])+(net|com|org|co|us|uk|xyz|info|de|tk|ga|cf)"
    # These are the domains which will not be blocked.
    whitelisted: "play.hypixel.net|www.minecraft.net"
    # A list of messages that will be sent to the player upon triggering the domain check
    # Available placeholders:
    # %PLAYER% , the player name

    # leave empty if none should be sent
    warning:
      - " &7[&eServer&7]&f: &7Your previous message has been deleted,"
      - " &7Hover here to see the reason &8[&f*&8]"
    # A list of messages that will be sent as hover message to the message above,
    # Available placeholders:
    # %PLAYER% , the player name
    # leave empty if none should be generated
    hover-warning:
      - "&7  [&eServer&7]"
      - "&7It looks like you've sent a &c&nforbidden&r&7 address..."
      - "&7Please don't to that again"
    # These are a list of executables objects that will trigger upon one of the players failing the check
    # you can set a list of commands that will be executed by the server.
    # you can set the field 'flags-trigger' to specify at how many flags the check should trigger
    # Available placeholders:
    # %PLAYER%, the player name.
    executables:
      - commands:
          - "tell %PLAYER% you just sent a forbidden address into the chat"
          - "tell %PLAYER% the next time this happens, this will result in a ban"
        flags: 1
      - commands:
          - "ban %PLAYER%"
        flags: 2
  addresses:
    enabled: true
    # This regex is used to blacklist all domains
    regex: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
    # These are the addresses that will not be blocked
    whitelisted: "127.0.0.1|0.0.0.0"
    # A list of messages that will be sent to the player upon triggering the ip check
    # Available placeholders:
    # %PLAYER% , the player name

    # leave empty if none should be sent
    warning:
      - " &7[&eServer&7]&f: &7Your previous message has been deleted,"
      - " &7Hover here to see the reason &8[&f*&8]"
    # A list of messages that will be sent as hover message to the message above,
    # Available placeholders:
    # %PLAYER% , the player name

    # leave empty if none should be generated
    hover-warning:
      - "&7  [&eServer&7]"
      - "&7It looks like you've sent a &c&nforbidden&r&7 ipv4..."
      - "&7Please don't to that again"
    executables:
      - commands:
          - "tell %PLAYER% you just sent a forbidden address into the chat"
          - "tell %PLAYER% the next time this happens, this will result in a ban"
        flags: 1
      - commands:
          - "ban %PLAYER%"
        flags: 2
  words:
    enabled: true
    # This is a list of blacklisted words that can't be used in the chat
    # if your message contains any of them, the check will be triggered.
    # NOTE: RegEx are supported here.
    # you can set the matcher using a RegEx , and the replace string, which will
    # be replaced into matched zone if found in the messages.
    # "What if I don't want to replace the messages?":
    # You can set the 'replace' parameter to "NONE"
    blacklisted:
      - pattern: "(?i)f(?=u(?=c(?=k)))"
        replace: 'd'

      - pattern: "(?i)shit"
        replace: "poop"

      - pattern: "(?i)d(?=ick(?!ens))"
        replace: "tr"
    # A list of messages that will be sent to the player upon triggering the words blacklist check
    # Available placeholders:
    # %PLAYER% , the player name
    # leave empty if none should be sent
    warning:
      - " &7[&eServer&7]&f: &7Your previous message has been deleted,"
      - " &7Hover here to see the reason &8[&f*&8]"
    # A list of messages that will be sent as hover message to the message above,
    # Available placeholders:
    # %PLAYER% , the player name
    # leave empty if none should be generated
    hover-warning:
      - "&7  [&eServer&7]"
      - "&7It looks like you've used a &c&nforbidden&r&7 word..."
      - "&7Please don't to that again"
    executables:
      - commands:
          - "tell %PLAYER% you just sent a forbidden word into the chat"
          - "tell %PLAYER% the next time this happens, this will result in a ban"
        flags: 2
      - commands:
          - "ban %PLAYER%"
        flags: 5
