# Config.yml
#
safechat:
  database: #PostgreSQL ONLY
    enabled: false
    username: 'username'
    password: 'password'
    port: 5432
    address: '127.0.0.1'
    database: 'database'
    table: 'safechat_data'
  domains:
    regex: "[a-z]+(\\s*)[.,]+(\\s*)[a-z]+(\\s*)[.,]+(\\s*)(com|net|org|it|uk|co|int|mil|edu|eu|info|xyz|space)"
    whitelisted: "play.hypixel.net|www.minecraft.net"
    warning:
      - " &7[&eServer&7]&f: &7Your previous message has been deleted,"
      - " &7Hover here to see the reason &8[&f*&8]"
    hover-warning:
      - "&7  [&eServer&7]"
      - "&7It looks like you've sent a &c&nforbidden&r&7 address..."
      - "&7Please don't to that again"
  addresses:
    regex: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
    whitelisted: "127.0.0.1|0.0.0.0"
    warning:
      - " &7[&eServer&7]&f: &7Your previous message has been deleted,"
      - " &7Hover here to see the reason &8[&f*&8]"
    hover-warning:
      - "&7  [&eServer&7]"
      - "&7It looks like you've sent a &c&nforbidden&r&7 ipv4..."
      - "&7Please don't to that again"

#    ______     ______     ______   ______     ______     __  __     ______     ______
#   /\  ___\   /\  __ \   /\  ___\ /\  ___\   /\  ___\   /\ \_\ \   /\  __ \   /\__  _\
#   \ \___  \  \ \  __ \  \ \  __\ \ \  __\   \ \ \____  \ \  __ \  \ \  __ \  \/_/\ \/
#    \/\_____\  \ \_\ \_\  \ \_\    \ \_____\  \ \_____\  \ \_\ \_\  \ \_\ \_\    \ \_\
#     \/_____/   \/_/\/_/   \/_/     \/_____/   \/_____/   \/_/\/_/   \/_/\/_/     \/_/
#
#   Plugin by TheViperShow. Custom-made.