[database]
address = "127.0.0.1" # Your database address.
port = 3306 # Your database port.
db-name = "my_database" # the name of the database to connect to.
sql-dialect = "MYSQL" # Your database SQL dialect.
username = "user" # The username of the database account this plugin will use.
password = "password" # The password of the database account this plugin will use.
timeout = 5000 # Maximum timeout in milliseconds.