name: 'SafeChat'
version: @version@
main: me.thevipershow.safechat.Safechat
authors: [TheViperShow]
description: 'Make your chat safe.'
api-version: '1.13'
commands:
  safechat:
    description: "Safechat's main command"
    usage: |
      /&lt;command&gt; reload - update the values from the config.yml
      /&lt;command&gt; top &lt;number&gt; [ipv4|domains|words]
      /&lt;command&gt; search [ipv4|domains|words] &lt;player&gt;
      /&lt;command&gt; search &lt;player&gt;
      /&lt;command&gt; clear &lt;player&gt;
      /&lt;command&gt; clear &lt;player&gt; [ipv4|domains|words]
    permission: 'safechat.command'
    permission-message: '§8[§6SafeChat§8]§7: §cYou are missing permissions'