name: Safechat
version: @version@
main: me.thevipershow.safechat.Safechat
depend: [SpigotChatLib]
authors: [TheViperShow]
description: Make your chat safe.
commands:
  safechat:
    description: "Safechat's main command"
    usage: "/<command> [search|top]"