name: 'SafeChat'
version: @version@
main: me.thevipershow.safechat.Safechat
authors: [TheViperShow]
description: 'Make your chat safe.'
api-version: '1.13'
commands:
  safechat:
    description: "Safechat's main command"
    usage: |
      /&lt;command&gt; reload - update the values from the config.yml
      /&lt;command&gt; sql top &lt;number&gt; [ipv4|domains|words]
      /&lt;command&gt; sql search [ipv4|domains|words] &lt;player&gt;